version: 2

sources:
  - name: dim_regions
  - name: dim_territories
  - name: dim_suppliers
  - name: dim_shippers
  - name: dim_categories
  - name: dim_products
  - name: dim_customers
  - name: dim_employees

  - name: fact_orders
  - name: fact_order_details
  - name: fact_employee_territories

models:
  - name: fact_orders
    description: "Staging model for fact_orders"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["orderID"]
      - type: FOREIGN_KEY
        columns: ["customerID", "employeeID", "shipVia"]
    columns:
      - name: orderID
      - name: customerID
      - name: employeeID
      - name: orderDate
      - name: requiredDate
      - name: shippedDate
      - name: shipVia
      - name: freight
      - name: shipName
      - name: shipAddress
      - name: shipCity
      - name: shipRegion
      - name: shipPostalCode
      - name: shipCountry
    tests:
      - not_null:
          - orderID
          - customerID
          - employeeID
          - orderDate
          - requiredDate
          - shippedDate
          - shipVia
          - freight
          - shipName
          - shipAddress
          - shipCity
          - shipRegion
          - shipPostalCode
          - shipCountry

  - name: fact_order_details
    description: "Staging model for fact_order_details"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: FOREIGN_KEY
        columns: ["orderID", "productID"]
    columns:
      - name: orderID
      - name: productID
      - name: unitPrice
      - name: quantity
      - name: discount
    tests:
      - not_null:
          - orderID
          - productID
          - unitPrice
          - quantity
          - discount

  - name: fact_employee_territories
    description: "Staging model for fact_employee_territories"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: FOREIGN_KEY
        columns: ["employeeID", "territoryID"]
    columns:
      - name: employeeID
      - name: territoryID
    tests:
      - not_null:
          - employeeID
          - territoryID

  - name: dim_regions
    description: "Staging model for dim_regions"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["regionID"]
    columns:
      - name: regionID
      - name: regionDescription
    tests:
      - not_null:
          - regionID
          - regionDescription

  - name: dim_territories
    description: "Staging model for dim_territories"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["territoryID"]
      - type: FOREIGN_KEY
        columns: ["regionID"]
    columns:
      - name: territoryID
      - name: territoryDescription
      - name: regionID
    tests:
      - not_null:
          - territoryID
          - territoryDescription
          - regionID

  - name: dim_suppliers
    description: "Staging model for dim_suppliers"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["supplierID"]
    columns:
      - name: supplierID
      - name: companyName
      - name: contactName
      - name: contactTitle
      - name: address
      - name: city
      - name: region
      - name: postalCode
      - name: country
      - name: phone
      - name: fax
      - name: homePage
    tests:
      - not_null:
          - supplierID
          - companyName
          - contactName
          - contactTitle
          - address
          - city
          - region
          - postalCode
          - country
          - phone
          - fax
          - homePage

  - name: dim_shippers
    description: "Staging model for dim_shippers"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["shipperID"]
    columns:
      - name: shipperID
      - name: companyName
      - name: phone
    tests:
      - not_null:
          - shipperID
          - companyName
          - phone

  - name: dim_categories
    description: "Staging model for dim_categories"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["categoryID"]
    columns:
      - name: categoryID
      - name: categoryName
      - name: description
      - name: picture
    tests:
      - not_null:
          - categoryID
          - categoryName
          - description
          - picture

  - name: dim_products
    description: "Staging model for dim_products"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["productID"]
      - type: FOREIGN_KEY
        columns: ["supplierID", "categoryID"]
    columns:
      - name: productID
      - name: productName
      - name: supplierID
      - name: categoryID
      - name: quantityPerUnit
      - name: unitPrice
      - name: unitsInStock
      - name: unitsOnOrder
      - name: reorderLevel
      - name: discontinued
    tests:
      - not_null:
          - productID
          - productName
          - supplierID
          - categoryID
          - quantityPerUnit
          - unitPrice
          - unitsInStock
          - unitsOnOrder
          - reorderLevel
          - discontinued

  - name: dim_customers
    description: "Staging model for dim_customers"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["customerID"]
    columns:
      - name: customerID
      - name: companyName
      - name: contactName
      - name: contactTitle
      - name: address
      - name: city
      - name: region
      - name: postalCode
      - name: country
      - name: phone
      - name: fax
    tests:
      - not_null:
          - customerID
          - companyName
          - contactName
          - contactTitle
          - address
          - city
          - region
          - postalCode
          - country
          - phone
          - fax

  - name: dim_employees
    description: "Staging model for dim_employees"
    config:
      materialized: table
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: ["employeeID"]
    columns:
      - name: employeeID
      - name: lastName
      - name: firstName
      - name: title
      - name: titleOfCourtesy
      - name: birthDate
      - name: hireDate
      - name: address
      - name: city
      - name: region
      - name: postalCode
      - name: country
      - name: homePhone
      - name: extension
      - name: photo
      - name: notes
      - name: reportsTo
      - name: photoPath
    tests:
      - not_null:
          - employeeID
          - lastName
          - firstName
          - title
          - titleOfCourtesy
          - birthDate
          - hireDate
          - address
          - city
          - region
          - postalCode
          - country
          - homePhone
          - extension
          - photo
          - notes
          - reportsTo
          - photoPath
